pipeline:
  build_image:
    image: docker:17.07.0
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t quay.io/ukhomeofficedigital/seccomp-config:${DRONE_BUILD_NUMBER} .

  image_to_quay:
    image: docker:17.07.0
    secrets: 
      - quay_user
      - quay_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u=$${QUAY_USER} -p=$${QUAY_PASSWORD} quay.io
      - docker tag quay.io/ukhomeofficedigital/seccomp-config:$${DRONE_BUILD_NUMBER} quay.io/ukhomeofficedigital/seccomp-config:$${DRONE_COMMIT_SHA}
      - docker tag quay.io/ukhomeofficedigital/seccomp-config:$${DRONE_BUILD_NUMBER} quay.io/ukhomeofficedigital/seccomp-config:latest
      - docker push quay.io/ukhomeofficedigital/seccomp-config:$${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/seccomp-config:latest
    when:
      branch: master
      event: push

  tag_image:
    image: docker:17.07.0
    secrets:
      - quay_user
      - quay_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u=$${QUAY_USER} -p=$${QUAY_PASSWORD} quay.io
      - docker tag quay.io/ukhomeofficedigital/seccomp-config:$${DRONE_BUILD_NUMBER} quay.io/ukhomeofficedigital/seccomp-config:$${DRONE_TAG}
      - docker push quay.io/ukhomeofficedigital/seccomp-config:$${DRONE_TAG}
    when:
      event: tag

  rollout_dev:
    image: quay.io/ukhomeofficedigital/kd:v0.3.1
    secrets:
      - dev_kube_server
      - dev_kube_token
    environment:
      - DRONE_DEPLOY_TO=dev
    commands:
      - bin/deploy.sh
    when:
      branch: master
      event: push

  rollout_test:
    image: quay.io/ukhomeofficedigital/kd:v0.3.1
    secrets:
      - test_kube_server
      - test_kube_token
    environment:
      - DRONE_DEPLOY_TO=test
    commands:
      - bin/deploy.sh
    when:
      branch: master
      event: push
